# .github/dependabot.yml
# Configuration with auto-merge enabled

# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
version: 2
updates:

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    # Workflow files stored in the default location of `.github/workflows`
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    allow:
      # Allow direct updates
      - dependency-type: "direct"
    ignore:
      # Ignore patch updates for all dependencies
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
    # Enable auto-merge for GitHub Actions updates
    rebase-strategy: auto

  # Maintain dependencies for pip
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
      time: "08:12"
    open-pull-requests-limit: 10
    allow:
      # Allow direct updates
      - dependency-type: "direct"
    ignore:
      # Ignore patch updates for all dependencies
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
    # Enable auto-merge for pip updates
    rebase-strategy: auto
